
# # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#
# target 'MakeStagram' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   pod 'Firebase/Core'
#   pod 'Firebase/Auth'
#   pod 'FirebaseUI/Auth'
#   pod 'Firebase/Database'
#   pod 'Firebase/Storage'
#   pod 'Firebase/Storage'



  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!

  target 'MakeStagram' do
      pod 'Firebase/Core'
      pod 'Firebase/Auth'
      pod 'FirebaseUI/Auth'
      pod 'Firebase/Database'
      pod 'Firebase/Storage'
      pod 'Firebase/Storage'
      pod 'Kingfisher', '~> 4.0'

  # Pods for MakeStagram

end
